version: "3.8"
services:
  keycloak:
    container_name: keycloak-bsh
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8081:8080"
    command:
      - start-dev
      - --import-realm
    volumes:
      - /home/iryna-kosiakovska/keycloak-import-data:/opt/keycloak/data/import
      - /home/iryna-kosiakovska/keycloak/data/h2:/opt/keycloak/data/h2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_PORT: 8080
      KC_HOSTNAME_URL: http://localhost:8081
      KC_HOSTNAME_ADMIN_URL: http://localhost:8081
      KC_HOSTNAME_STRICT_BACKCHANNEL: null
      KC_HTTP_RELATIVE_PATH: /
      KC_HTTP_ENABLED: null
      KC_HEALTH_ENABLED: null
      KC_METRICS_ENABLED: null

